// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Grs.BioRestock.Infrastructure.Contexts;
using Grs.BioRestock.Infrastructure.Extensions;
using Grs.BioRestock.Domain.Entities;

namespace Grs.BioRestock.Infrastructure.Contexts
{
    public partial class UniContext
    {

        public UniContext(DbContextOptions<UniContext> options)
            : base(options)
        {
        }
        public virtual DbSet<DemandeSignature> DemandeSignatures { get; set; }
        public virtual DbSet<DocumentSignature> DocumentSignatures { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnIdentityModelCreating(modelBuilder);

            modelBuilder.Entity<Domain.Entities.DemandeSignature>(entity =>
            {
                entity.ToTable("DemandeSignature");
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<Domain.Entities.DocumentSignature>(entity =>
            {
                entity.ToTable("DocumentSignature");
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });


        }

        //protected override void OnModelCreating(ModelBuilder modelBuilder)
        //{
        //    OnIdentityModelCreating(modelBuilder);

        //    OnModelCreatingGenerated(modelBuilder);


        //   // OnModelCreatingPartial(modelBuilder);
        //}

        //partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}